// Code generated by protoc-gen-go.
// source: Nachricht.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	Nachricht.proto

It has these top-level messages:
	Nachricht
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Nachricht_NachrichtenTyp int32

const (
	Nachricht_KONTROLLNACHRICHT   Nachricht_NachrichtenTyp = 0
	Nachricht_ANWENDUNGSNACHRICHT Nachricht_NachrichtenTyp = 1
)

var Nachricht_NachrichtenTyp_name = map[int32]string{
	0: "KONTROLLNACHRICHT",
	1: "ANWENDUNGSNACHRICHT",
}
var Nachricht_NachrichtenTyp_value = map[string]int32{
	"KONTROLLNACHRICHT":   0,
	"ANWENDUNGSNACHRICHT": 1,
}

func (x Nachricht_NachrichtenTyp) Enum() *Nachricht_NachrichtenTyp {
	p := new(Nachricht_NachrichtenTyp)
	*p = x
	return p
}
func (x Nachricht_NachrichtenTyp) String() string {
	return proto.EnumName(Nachricht_NachrichtenTyp_name, int32(x))
}
func (x *Nachricht_NachrichtenTyp) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Nachricht_NachrichtenTyp_value, data, "Nachricht_NachrichtenTyp")
	if err != nil {
		return err
	}
	*x = Nachricht_NachrichtenTyp(value)
	return nil
}

type Nachricht_KontrollTyp int32

const (
	// Use this option if you want to assign multiple definitions for the same value
	// For example: "INITIALISIEREN = 0;" && "START = 0;".
	// option allow_alias = true;
	Nachricht_INITIALISIEREN Nachricht_KontrollTyp = 0
	Nachricht_BEENDEN        Nachricht_KontrollTyp = 1
)

var Nachricht_KontrollTyp_name = map[int32]string{
	0: "INITIALISIEREN",
	1: "BEENDEN",
}
var Nachricht_KontrollTyp_value = map[string]int32{
	"INITIALISIEREN": 0,
	"BEENDEN":        1,
}

func (x Nachricht_KontrollTyp) Enum() *Nachricht_KontrollTyp {
	p := new(Nachricht_KontrollTyp)
	*p = x
	return p
}
func (x Nachricht_KontrollTyp) String() string {
	return proto.EnumName(Nachricht_KontrollTyp_name, int32(x))
}
func (x *Nachricht_KontrollTyp) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Nachricht_KontrollTyp_value, data, "Nachricht_KontrollTyp")
	if err != nil {
		return err
	}
	*x = Nachricht_KontrollTyp(value)
	return nil
}

type Nachricht struct {
	SourceIP          *string                   `protobuf:"bytes,1,req,name=sourceIP" json:"sourceIP,omitempty"`
	SourcePort        *int32                    `protobuf:"varint,2,req,name=sourcePort" json:"sourcePort,omitempty"`
	SourceID          *int32                    `protobuf:"varint,3,req,name=sourceID" json:"sourceID,omitempty"`
	NachrichtenTyp    *Nachricht_NachrichtenTyp `protobuf:"varint,4,req,name=nachrichtenTyp,enum=protobuf.Nachricht_NachrichtenTyp,def=1" json:"nachrichtenTyp,omitempty"`
	KontrollTyp       *Nachricht_KontrollTyp    `protobuf:"varint,5,opt,name=kontrollTyp,enum=protobuf.Nachricht_KontrollTyp,def=0" json:"kontrollTyp,omitempty"`
	NachrichtenInhalt *string                   `protobuf:"bytes,6,req,name=nachrichtenInhalt" json:"nachrichtenInhalt,omitempty"`
	ZeitStempel       *string                   `protobuf:"bytes,7,opt,name=zeitStempel" json:"zeitStempel,omitempty"`
	XXX_unrecognized  []byte                    `json:"-"`
}

func (m *Nachricht) Reset()         { *m = Nachricht{} }
func (m *Nachricht) String() string { return proto.CompactTextString(m) }
func (*Nachricht) ProtoMessage()    {}

const Default_Nachricht_NachrichtenTyp Nachricht_NachrichtenTyp = Nachricht_ANWENDUNGSNACHRICHT
const Default_Nachricht_KontrollTyp Nachricht_KontrollTyp = Nachricht_INITIALISIEREN

func (m *Nachricht) GetSourceIP() string {
	if m != nil && m.SourceIP != nil {
		return *m.SourceIP
	}
	return ""
}

func (m *Nachricht) GetSourcePort() int32 {
	if m != nil && m.SourcePort != nil {
		return *m.SourcePort
	}
	return 0
}

func (m *Nachricht) GetSourceID() int32 {
	if m != nil && m.SourceID != nil {
		return *m.SourceID
	}
	return 0
}

func (m *Nachricht) GetNachrichtenTyp() Nachricht_NachrichtenTyp {
	if m != nil && m.NachrichtenTyp != nil {
		return *m.NachrichtenTyp
	}
	return Default_Nachricht_NachrichtenTyp
}

func (m *Nachricht) GetKontrollTyp() Nachricht_KontrollTyp {
	if m != nil && m.KontrollTyp != nil {
		return *m.KontrollTyp
	}
	return Default_Nachricht_KontrollTyp
}

func (m *Nachricht) GetNachrichtenInhalt() string {
	if m != nil && m.NachrichtenInhalt != nil {
		return *m.NachrichtenInhalt
	}
	return ""
}

func (m *Nachricht) GetZeitStempel() string {
	if m != nil && m.ZeitStempel != nil {
		return *m.ZeitStempel
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.Nachricht_NachrichtenTyp", Nachricht_NachrichtenTyp_name, Nachricht_NachrichtenTyp_value)
	proto.RegisterEnum("protobuf.Nachricht_KontrollTyp", Nachricht_KontrollTyp_name, Nachricht_KontrollTyp_value)
}
